"""
pina_photodiode_mesh.py

Solves the 2D P-N Photodiode equilibrium (dark, V=0) case using PINA.
This script is designed to load and use the mesh generated by
'gmesh_diode2d.py'.

!! REQUIRES 'gmsh_diode2d.msh' to exist in the same directory.
!! Run 'python gmesh_diode2d.py' first (with show_gui=False).
"""

import torch
import numpy as np
import pina
from pina.problem import PINNProblem
from pina.model import FNN
from pina.trainer import Trainer
from pina.plotter import Plotter
from pina.solvers import PINN
from pina.callbacks import MetricTracker

# ======================================================================
# 1. PHYSICAL CONSTANTS (from diode_deepxde_enhance.py)
# ======================================================================
q = 1.602e-19
k_B = 1.381e-23
eps_0 = 8.854e-14
T = 300.0
V_t = k_B * T / q  # ~0.0259 V

eps_r = 11.7
epsilon = eps_r * eps_0
n_i = 1.0e10
n_i_sq = n_i ** 2

mu_n = 1400.0
mu_p = 450.0
D_n = mu_n * V_t
D_p = mu_p * V_t

tau_n = 1.0e-6
tau_p = 1.0e-6

# ======================================================================
# 2. GEOMETRY & DOPING (from diode_deepxde_enhance.py)
# ======================================================================
# These definitions are used by the doping_profile function
n_plus_thickness = 0.5 * 1e-4
p_thickness = 50.0 * 1e-4
p_plus_thickness = 10.0 * 1e-4

y_j1_cm = n_plus_thickness
y_j2_cm = n_plus_thickness + p_thickness

N_D_nplus = 1e19
N_A_p = 1e16
N_A_pplus = 1e19

# Normalization scale for PDE
scale_recomb = N_D_nplus / tau_n  # ~1e25 cm⁻³/s


def doping_profile(x_in):
    """Net doping N_D - N_A, as a PINA-compatible function."""
    y = x_in.extract(['y'])

    # Ensure y is a tensor
    if not isinstance(y, torch.Tensor):
        y = torch.tensor(y, dtype=torch.float32)

    N_D = torch.where(y <= y_j1_cm,
                      torch.full_like(y, N_D_nplus),
                      torch.full_like(y, 0.0))

    N_A_val = torch.where(y <= y_j2_cm,
                          torch.full_like(y, N_A_p),
                          torch.full_like(y, N_A_pplus))
    N_A = torch.where(y > y_j1_cm, N_A_val, torch.full_like(y, 0.0))

    return (N_D - N_A).reshape(-1, 1)


# ======================================================================
# 3. PDE SYSTEM (Adapted for PINA)
# ======================================================================

def pde_system(input_pts, output_vars):
    """2D drift-diffusion equations."""

    # Extract variables
    psi = output_vars.extract(['psi'])
    log_n = output_vars.extract(['log_n'])
    log_p = output_vars.extract(['log_p'])

    # Clamp log values for numerical stability
    log_n = torch.clamp(log_n, min=np.log(1e5), max=np.log(1e20))
    log_p = torch.clamp(log_p, min=np.log(1e5), max=np.log(1e20))

    n = torch.exp(log_n)
    p = torch.exp(log_p)

    # --- POISSON'S EQUATION ---
    grad_psi = pina.grad(psi, input_pts)
    laplacian_psi = pina.div(grad_psi, input_pts)

    N_net = doping_profile(input_pts)
    rho = q * (p - n + N_net)
    norm_poisson = 1.0 / (q * N_A_pplus)
    eq1_poisson = (epsilon * laplacian_psi + rho) * norm_poisson

    # --- RECOMBINATION & GENERATION ---
    U_num = n * p - n_i_sq
    U_den = tau_p * (n + n_i) + tau_n * (p + n_i)
    U = U_num / (U_den + 1e-10)

    # G_func (Dark simulation)
    G = torch.zeros_like(U)

    # --- CONTINUITY EQUATIONS ---
    grad_n = pina.grad(n, input_pts)
    grad_p = pina.grad(p, input_pts)

    # Electron
    Jn = -q * mu_n * n * grad_psi + q * D_n * grad_n
    div_Jn = pina.div(Jn, input_pts)
    eq2_electron = ((div_Jn / q) - U + G) / scale_recomb

    # Hole
    Jp = -q * mu_p * p * grad_psi - q * D_p * grad_p
    div_Jp = pina.div(Jp, input_pts)
    eq3_hole = (-(div_Jp / q) - U + G) / scale_recomb

    return {
        'poisson': eq1_poisson,
        'electron_continuity': eq2_electron,
        'hole_continuity': eq3_hole
    }


# ======================================================================
# 4. PROBLEM DEFINITION CLASS (The PINA way)
# ======================================================================

class PhotodiodeProblem(PINNProblem):
    # --- Define I/O variables ---
    input_variables = ['x', 'y']
    output_variables = ['psi', 'log_n', 'log_p']

    # --- Equilibrium (V=0) BC values ---
    V_bias = 0.0
    V_bi_cathode = V_t * np.log(N_D_nplus / n_i)
    log_n_eq_cathode = np.log(N_D_nplus)
    log_p_eq_cathode = np.log(n_i_sq / N_D_nplus)

    V_bi_anode = -V_t * np.log(N_A_pplus / n_i)
    log_n_eq_anode = np.log(n_i_sq / N_A_pplus)
    log_p_eq_anode = np.log(N_A_pplus)

    psi_cathode_val = V_bi_cathode + V_bias
    psi_anode_val = V_bi_anode

    # --- Load the mesh ---
    # This is the crucial part: PINA reads the .msh file
    # and automatically understands the physical groups.
    try:
        mesh = pina.Mesh("gmsh_diode2d.msh")
    except FileNotFoundError:
        print("ERROR: 'gmsh_diode2d.msh' not found.")
        print("Please run 'python gmesh_diode2d.py' first to generate the mesh.")
        exit(1)

    # --- Define spatial domain & PDE ---
    # We apply the PDE to all semiconductor regions
    spatial_domain = mesh.domains['n_plus_region'] + \
                     mesh.domains['p_region'] + \
                     mesh.domains['p_plus_region']

    pde_equation = pina.Condition(
        location=spatial_domain,
        equation=pina.Equation(pde_system)
    )

    # --- Define Boundary Conditions (Dirichlet) ---
    # We apply BCs to the named boundaries from the mesh

    # Cathode
    bc_psi_cathode = pina.Condition(
        location=mesh.boundaries['cathode'],
        equation=pina.Equation(lambda input_pts, psi: psi - psi_cathode_val, "Dirichlet")
    )
    bc_logn_cathode = pina.Condition(
        location=mesh.boundaries['cathode'],
        equation=pina.Equation(lambda input_pts, log_n: log_n - log_n_eq_cathode, "Dirichlet")
    )
    bc_logp_cathode = pina.Condition(
        location=mesh.boundaries['cathode'],
        equation=pina.Equation(lambda input_pts, log_p: log_p - log_p_eq_cathode, "Dirichlet")
    )

    # Anode
    bc_psi_anode = pina.Condition(
        location=mesh.boundaries['anode'],
        equation=pina.Equation(lambda input_pts, psi: psi - psi_anode_val, "Dirichlet")
    )
    bc_logn_anode = pina.Condition(
        location=mesh.boundaries['anode'],
        equation=pina.Equation(lambda input_pts, log_n: log_n - log_n_eq_anode, "Dirichlet")
    )
    bc_logp_anode = pina.Condition(
        location=mesh.boundaries['anode'],
        equation=pina.Equation(lambda input_pts, log_p: log_p - log_p_eq_anode, "Dirichlet")
    )

    # --- Define Insulating Surfaces (Neumann) ---
    # From your 'photodiode.md' guide (Section 5.2):
    # "No normal electric field: ∇ψ ⋅ n̂ = 0"
    # We apply this to all non-contact surfaces.

    insulating_surfaces = mesh.boundaries['top_surface'] + \
                          mesh.boundaries['left_side'] + \
                          mesh.boundaries['right_side']

    # Zero normal gradient for all 3 variables
    # (psi, n, p) -> (psi, log_n, log_p)
    bc_neumann_psi = pina.Condition(
        location=insulating_surfaces,
        equation=pina.Equation(lambda input_pts, normal, psi: pina.normal_derivative(psi, input_pts, normal), "Neumann")
    )
    bc_neumann_logn = pina.Condition(
        location=insulating_surfaces,
        equation=pina.Equation(lambda input_pts, normal, log_n: pina.normal_derivative(log_n, input_pts, normal),
                               "Neumann")
    )
    bc_neumann_logp = pina.Condition(
        location=insulating_surfaces,
        equation=pina.Equation(lambda input_pts, normal, log_p: pina.normal_derivative(log_p, input_pts, normal),
                               "Neumann")
    )

    # --- Compile all conditions ---
    conditions = {
        'pde_domain': pde_equation,
        'bc_psi_cathode': bc_psi_cathode,
        'bc_logn_cathode': bc_logn_cathode,
        'bc_logp_cathode': bc_logp_cathode,
        'bc_psi_anode': bc_psi_anode,
        'bc_logn_anode': bc_logn_anode,
        'bc_logp_anode': bc_logp_anode,
        'bc_neumann_psi': bc_neumann_psi,
        'bc_neumann_logn': bc_neumann_logn,
        'bc_neumann_logp': bc_neumann_logp,
    }


# ======================================================================
# 5. MAIN EXECUTION (Train and Plot)
# ======================================================================

if __name__ == "__main__":
    print("=" * 70)
    print("PINA 2D Photodiode Simulation (Equilibrium, V=0, Dark)")
    print(f"Using Mesh: {PhotodiodeProblem.mesh.filename}")
    print(f"  Regions: {list(PhotodiodeProblem.mesh.domains.keys())}")
    print(f"  Boundaries: {list(PhotodiodeProblem.mesh.boundaries.keys())}")
    print("=" * 70)

    # 1. Initialize Problem
    problem = PhotodiodeProblem()

    # 2. Initialize Model (FNN)
    model = FNN(
        input_dimensions=len(problem.input_variables),
        output_dimensions=len(problem.output_variables),
        layers=[64] * 4,  # [64, 64, 64, 64]
        activation=torch.nn.Tanh
    )

    # 3. Initialize PINN Solver
    pinn_solver = PINN(
        problem=problem,
        model=model,
        # Use more points since we're sampling from a complex mesh
        sampler_batches=1000,
        pde_points=20000,  # More points inside the domain
        boundary_points=5000,  # More points on the boundaries
        # Set weights: high for BCs, low for PDE
        loss_weights={
            'pde_domain': 0.1,
            'bc_psi_cathode': 100.0,
            'bc_logn_cathode': 100.0,
            'bc_logp_cathode': 100.0,
            'bc_psi_anode': 100.0,
            'bc_logn_anode': 100.0,
            'bc_logp_anode': 100.0,
            'bc_neumann_psi': 10.0,
            'bc_neumann_logn': 10.0,
            'bc_neumann_logp': 10.0,
        }
    )

    # 4. Initialize Trainer
    trainer = Trainer(
        solver=pinn_solver,
        accelerator="auto",  # "cpu", "gpu", "mps"
        callbacks=[MetricTracker()],
        max_epochs=10000,  # ADAM
        optimizer_kwargs={'lr': 1e-4}
    )

    # 5. Train
    print("Starting training (Adam)...")
    trainer.train()

    # Optional: L-BFGS refinement
    print("\nStarting refinement (L-BFGS)...")
    trainer.train(
        max_epochs=5000,  # L-BFGS steps
        optimizer=torch.optim.LBFGS,
        optimizer_kwargs={
            'lr': 1.0,
            'max_iter': 200,  # L-BFGS internal iterations
            'history_size': 100
        }
    )
    print("✓ Training complete!")

    # 6. Plot results
    print("\nPlotting results...")
    plotter = Plotter(pinn_solver)

    # Plot over the entire mesh domain
    plotter.plot_mesh(
        variables=['psi', 'log_n', 'log_p'],
        filename="pina_photodiode_results.png"
    )
    print("✓ Saved: pina_photodiode_results.png")

    # Plot a 1D cut through the middle (x = 50 um = 0.005 cm)
    plotter.plot_1d(
        locations={'x': 0.005},
        variables=['psi', 'log_n', 'log_p'],
        filename="pina_photodiode_1D_cut.png"
    )
    print("✓ Saved: pina_photodiode_1D_cut.png")
    print("\n✅ PINA simulation finished!\n")